name: CI workflow

on: pull_request

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout rspository
        uses: actions/checkout@v4

      - name: Install
        run: npm ci

      - name: Test e2e
        run: npm run test:e2e:ci
